#!/bin/sh

####################################################################################################
# $ sh/myrun subject path/to/subject #loop rev s3 ec2
#
# subject        : ID representing subject
# path/to/subject: absolute or relative path to subject root directory
# #loop          : once if 0~9, otherwise each
# rev (optional) : -cp subject:AdaMu if given (default: -cp AdaMu:subject)
# s3  (optional) : upload results to S3 if given (note: edit "sh/s3.uri to change S3 destination")
# ec2 (optional) : self-stop EC2 instance
#
# Ex.
# $ sh/myrun cli ../../commons/commons-cli-1.2-src/ 10 s3
# $ sh/myrun math3 ../../commons/commons-math3-3.4.1-src/ 4 rev s3 ec2
####################################################################################################

# S3_URI="s3://adamu/20160803"
S3_URI=`cat sh/s3.uri`

## Copy maven dependencies if not exits
ADAMU_PWD=$(pwd)
ADAMU_SUBJECT_DEPENDENCY_DIR="${2}target/dependency"
if [ -e ${ADAMU_SUBJECT_DEPENDENCY_DIR} ]; then
	echo "Found dependencies on subject test project"
else
	cd ${2}
	mvn dependency:copy-dependencies
	cd ${ADAMU_PWD}
fi

## Create class path
PRIORI_CP=""
if [ -f ${2}target/dependency/xercesImpl-2.4.0.jar ] && [ -f ${2}target/dependency/xml-apis-1.3.04.jar ]; then
	PRIORI_CP="${2}target/dependency/xercesImpl-2.4.0.jar:${2}target/dependency/xml-apis-1.3.04.jar"
fi
ADAMU_CP="target/classes:target/test-classes:target/dependency/*"
SUBJECT_CP="${2}target/classes:${2}target/test-classes:${2}target/dependency/*"

if [ "rev" = "${4}" ] || [ "rev" = "${5}" ] || [ "rev" = "${6}" ]; then
	echo "@class-path: subject > AdaMu"
	ADAMU_CLASSPATH="${SUBJECT_CP}:${ADAMU_CP}"
else
	echo "@class-path: AdaMu > subject"
	ADAMU_CLASSPATH="${PRIORI_CP}:${ADAMU_CP}:${SUBJECT_CP}"
fi

if [ ${3} -ge 0 ] && [ ${3} -le 9 ]; then
	LOOP_NUM=${3}
else
	LOOP_NUM=(0 1 2 3 4 5 6 7 8 9)
fi

## for randomness
for i in ${LOOP_NUM[@]}
do

if [ -e /tmp/testAboveThresholdSpecifiedRepository/ ]; then
  rm -r /tmp/testAboveThresholdSpecifiedRepository/
fi

## Run AdaMu
/usr/bin/java \
  -Xms6400m \
  -cp ${ADAMU_CLASSPATH} \
  -Djava.util.logging.config.file=target/classes/logging.properties \
  jp.mzw.adamu.CLI run ${1}

## Copy results
ADAMU_DIR="res/rawdata/latest/${1}"
if [ -d ${ADAMU_DIR} ]; then
	rm -r ${ADAMU_DIR}
fi
if [ -d ${ADAMU_DIR}_${i} ]; then
	rm -r ${ADAMU_DIR}_${i}
fi
mkdir -p ${ADAMU_DIR}
cp logs/latest/* ${ADAMU_DIR}

## Run R to visualize results
ADAMU_R_GRAPH_FILE="res/rawdata/latest/${1}/graph.R"
if [ -f ${ADAMU_R_GRAPH_FILE} ]; then
	rm ${ADAMU_R_GRAPH_FILE}
fi
echo "setwd(\"${ADAMU_DIR}/\")\n" >> ${ADAMU_R_GRAPH_FILE}
cat res/commands/graph.template.R >> ${ADAMU_R_GRAPH_FILE}
R --vanilla --slave < ${ADAMU_R_GRAPH_FILE}

## for randomness
mv ${ADAMU_DIR} ${ADAMU_DIR}_${i}
if [ "s3" = "${4}" ] || [ "s3" = "${5}" ] || [ "s3" = "${6}" ]; then
	echo "Copy results to S3"
	aws s3 cp ${ADAMU_DIR}_${i} ${S3_URI}/${1}_${i} --recursive
fi
done

# echo "All finished: ${1}" | /usr/sbin/sendmail yuta@mzw.jp

if [ "ec2" = "${4}" ] || [ "ec2" = "${5}" ] || [ "ec2" = "${6}" ]; then
	echo "Stop EC2"
	sh/ec2-stop
fi
