#!/bin/sh

## Copy maven dependencies if not exits
ADAMU_PWD=$(pwd)
ADAMU_SUBJECT_DEPENDENCY_DIR="${2}target/dependency"
if [ -e ${ADAMU_SUBJECT_DEPENDENCY_DIR} ]; then
	echo "Found dependencies on subject test project"
else
	cd ${2}
	mvn dependency:copy-dependencies
	cd ${ADAMU_PWD}
fi

## Create class path
ADAMU_CP="target/classes:target/test-classes:target/dependency/*"
SUBJECT_CP="${2}target/classes:${2}target/test-classes:${2}target/dependency/*"
ADAMU_CLASSPATH="${ADAMU_CP}:${SUBJECT_CP}"

if [ "" != "${3}" ]; then
	ADAMU_CLASSPATH="${ADAMU_CLASSPATH}:${3}"
fi

## for randomness
for i in 0 1 2 3 4 5 6 7 8 9
do

if [ -e /tmp/testAboveThresholdSpecifiedRepository/ ]; then
  rm -r /tmp/testAboveThresholdSpecifiedRepository/
fi

## Run AdaMu
/usr/bin/java \
  -Xms6400m \
  -cp ${ADAMU_CLASSPATH} \
  jp.mzw.adamu.CLI run ${1} \
  1> /dev/null 2> /dev/null

## Copy results
ADAMU_DIR="res/rawdata/latest/${1}"
mkdir -p ${ADAMU_DIR}
cp logs/latest/* ${ADAMU_DIR}

## Run R to visualize results
ADAMU_R_GRAPH_FILE="res/rawdata/latest/${1}/graph.R"
if [ -f ${ADAMU_R_GRAPH_FILE} ]; then
	rm ${ADAMU_R_GRAPH_FILE}
fi
echo "setwd(\"${ADAMU_DIR}/\")\n" >> ${ADAMU_R_GRAPH_FILE}
cat res/commands/graph.template.R >> ${ADAMU_R_GRAPH_FILE}
R --vanilla --slave < ${ADAMU_R_GRAPH_FILE}

## for randomness
mv ${ADAMU_DIR} ${ADAMU_DIR}_${i}
done
