#!/bin/sh

PATH_TO_APACHE_COMMONS_DIR=/Users/yuta/workspace/apache-commons/

if [ ${#} -le 1 ] || [ ${#} -gt 3 ]; then
	echo "command [subject] [set of mutation operators] [(optional) disabled]"
	exit
fi

# Subject
if [ ${1} = "cli" ]; then
	subject=commons-cli
elif [ ${1} = "math" ]; then
	subject=commons-math
else
	echo "Give valid target, e.g., 'cli'"
	exit
fi
PATH_TO_SUBJECT_DIR="${PATH_TO_APACHE_COMMONS_DIR}${subject}"
## Compile subject
cd ${PATH_TO_SUBJECT_DIR}
if [ -e ${PATH_TO_SUBJECT_DIR}/target/classes ] && [ -e ${PATH_TO_SUBJECT_DIR}/target/test-classes ] && [ -e ${PATH_TO_SUBJECT_DIR}/target/dependency ]; then
	echo "Already compiled: ${subject}"
else
	mvn compile test-compile dependency:copy-dependencies
fi
## Go back to AdaMu directory
cd - > /dev/null
if [ -e target/classes ] && [ -e target/test-classes ] && [ -e target/dependency ]; then
	echo "Already compiled: AdaMu"
else
	mvn compile test-compile dependency:copy-dependencies
fi

# Set of mutation operators
if [ ${2} = "defaults" ]; then
	op="defaults"
elif [ ${2} = "stronger" ]; then
	op="stronger"
elif [ ${2} = "all" ]; then
	op="all"
else
	echo "Give valid set of mutation operators (default, stronger, or all)"
	exit
fi

## Enable AdaMu
if [ ${#} -gt 2 ]; then
	enalbed=${3}
fi


# AdaMu
# php sh/slack.php AdaMu "start to run: \"${subject}\" with \"${op}\" mutation operator set" > /dev/null
## Configure class path
cp="$(pwd)/target/classes"
cp="${cp}:$(pwd)/target/test-classes"
cp="${cp}:$(pwd)/target/dependency/*"
cp="${cp}:${PATH_TO_SUBJECT_DIR}/target/classes"
cp="${cp}:${PATH_TO_SUBJECT_DIR}/target/test-classes"
cp="${cp}:${PATH_TO_SUBJECT_DIR}/target/dependency/*"
## Run at subject directory due to relative file path problem
cd ${PATH_TO_SUBJECT_DIR}
## Run AdaMu
/usr/bin/java \
	-Xms6400m \
	-cp ${cp} \
	-Djava.util.logging.config.file=target/classes/logging.properties \
	jp.mzw.adamu.CLI run ${PATH_TO_SUBJECT_DIR} ${op} ${enalbed}
## Go back to AdaMu directory
cd - > /dev/null
